routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('massketting.particles.index');
});
Route::post('/pending','Auth\RegisterController@registerPending')->name('pending');

Route::get('/pending_users', "UserController@showPending");
Route::post('/legitice_user', 'UserController@legiticeUser');
Route::post('/search_penders', "UserController@searchPenders");

Route::get('/users', "UserController@showUsers");
Route::post('/search_users', "UserController@searchUsers");

Route::resource('/creative', "CreativeController", ['except' => [
     'destroy'
]]);


Auth::routes();


Route::get('/logout', 'HomeController@logout')->name('logout');

Route::prefix('home')->middleware(['auth'])->group(function() {
Route::get('/', 'HomeController@index')->name('home');
Route::get('/approval','HomeController@approveAccount');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lumino - Login</title>
	<link href="{{ asset('lumino/lumino/css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ asset('lumino/lumino/css/datepicker3.css') }}" rel="stylesheet">
	<link href="{{ asset('lumino/lumino/css/styles.css') }}" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="row">
	@if(Session::has('success'))
	<p align="center" class="alert alert-success">{!!session('success')!!}</p>
	@endif
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">

			@yield('content')
			
		</div><!-- /.col-->
	</div><!-- /.row -->	
	

<script src="{{ asset('lumino/lumino/js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ asset('lumino/lumino/js/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/layouts/frontend.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Massketing</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
@yield('css')
<!-- Bootstrap -->
<link href="{{asset('massketing/world-map/css/bootstrap.min.css')}}" rel="stylesheet">

<!-- Font Awesome Icons -->
<link href="{{asset('massketing/world-map/css/font-awesome.min.css')}}" rel="stylesheet">

<!-- Menu Corner Morph -->
<link rel="stylesheet" type="text/css" href="{{asset('massketing/world-map/css/cornermorph.css')}}" />

<!-- Custom Style Sheet -->
<link href="{{asset('massketing/world-map/css/style.css')}}" rel="stylesheet">

<!--<link rel="shortcut icon" href="img/favicon.png">-->

</head>

<body>

<!-- =========================
     Pre-loader 
============================== -->

<div id="loading">
  <div id="loading-center">
    <div id="loading-center-absolute">
      <div id="object"></div>
    </div>
  </div>
</div>
<div class="menu-wrap">
  <nav class="menu">
    <ul class="link-list">
      <li><a class="scroll" href="#header">Massketing Intro</a></li>
      <li><a class="scroll" href="#we-build">Building Relationship</a></li>
      <li><a class="scroll" href="#what-we-do">What We Do</a></li>
      <li><a class="scroll" href="#powerful-tools">Powerful Tools</a></li>
      <li><a class="scroll" href="#popular">Real Time Reports</a></li>
      <li><a class="scroll" href="#our-client">Our Clients</a></li>
      <li><a class="scroll" href="#affiliate">Get Affialiate</a></li>
    </ul>
  </nav>
</div>
<button class="menu-button" id="open-button"><i class="fa fa-bars" aria-hidden="true"></i></button>
<div class="content-wrap"></div>
<!-- =========================
     Background Particles 
============================== -->
<div id="particles-js"></div>

<!-- =========================
     Section1 - Header   
============================== -->
@yield('content')

<!-- =========================
     Section8 - Footer  
============================== -->
<footer id="copy-right">
  <div class="container" style="margin-top: 5%">
    <div class="row">
      <div class="col-md-3 column"> 
        <ul class="social-icon">
          <li><a href="#"><i class="fa fa-envelope"></i><span></span></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i><span></span></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i><span></span></a></li>
          <li><a href="#"><i class="fa fa-rss"></i><span></span></a></li>
          <li><a href="#"><i class="fa fa-twitter"><span></span></i></a></li>
          <li><a href="#"><i class="fa fa-youtube"><span></span></i></a></li>
        </ul>
      </div>
      <div class="col-md-3 column"> 
        <ul style="list-style-type: none">
          <li>- About Us</li>
          <li>- Contact Us</li>
        </ul>
      </div>
      <div class="col-md-3 column"> 
        <ul style="list-style-type: none">
          <li>- Transfer-usa.com</li>
          <li>- Affiliates Blog</li>
        </ul>
      </div>
      <div class="col-md-3 column"> 
        end images
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 column">
        <p>
          Copyright &copy; 2018. Transfer USA Logo is registered trademark of XCA Travel, S.A. de C.V
          <br >
          <a href="">Terms and Conditions - Privacy Policy</a>
        </p>
      </div>
    </div>
  </div>
</footer>

<!-- =========================
     Scripts   
============================== --> 
<!-- Jquery --> 
<script src="{{asset('massketing/world-map/js/jquery.min.js')}}"></script> 

<!-- Jquery Easing --> 
<script src="{{asset('massketing/world-map/js/jquery.easing.min.js')}}"></script> 

<!-- Bootstrap --> 
<script type="text/javascript" src="{{asset('massketing/world-map/js/bootstrap.min.js')}}"></script> 

<!-- Validate JS --> 
<script src="{{asset('massketing/world-map/js/jquery.validate.min.js')}}"></script> 

<!-- Ajax Form JS --> 
<script src="{{asset('massketing/world-map/js/jquery.form.js')}}"></script> 

<!-- Retina Ready --> 
<script src="{{asset('massketing/world-map/js/retina.min.js')}}"></script> 

<!-- Background Particles --> 
<script src="{{asset('massketing/world-map/js/particles.js')}}"></script> 
<script src="{{asset('massketing/world-map/js/particles-config.js')}}"></script> 

<!-- Scroll Reveal --> 
<script src="{{asset('massketing/world-map/js/scrollreveal.min.js')}}"></script> 

<!-- Menu Corner Morph --> 
<script src="{{asset('massketing/world-map/js/classie.js')}}"></script> 
<script src="{{asset('massketing/world-map/js/cornermorph.js')}}"></script> 

<!-- Custom --> 
<script src="{{asset('massketing/world-map/js/custom.js')}}"></script>
@yield('js')
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lumino - Dashboard</title>
	<link href="{{ asset('lumino/lumino/css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ asset('lumino/lumino/css/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ asset('lumino/lumino/css/datepicker3.css') }}" rel="stylesheet">
	<link href="{{ asset('lumino/lumino/css/styles.css') }}" rel="stylesheet">
	x
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	@yield('css')
</head>
<body>
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="#"><span>Lumino</span>Admin</a>
				<ul class="nav navbar-top-links navbar-right">
					<li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
						<em class="fa fa-envelope"></em><span class="label label-danger">15</span>
					</a>
						<ul class="dropdown-menu dropdown-messages">
							<li>
								<div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
									<img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
									</a>
									<div class="message-body"><small class="pull-right">3 mins ago</small>
										<a href="#"><strong>John Doe</strong> commented on <strong>your photo</strong>.</a>
									<br /><small class="text-muted">1:24 pm - 25/03/2015</small></div>
								</div>
							</li>
							<li class="divider"></li>
							<li>
								<div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
									<img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
									</a>
									<div class="message-body"><small class="pull-right">1 hour ago</small>
										<a href="#">New message from <strong>Jane Doe</strong>.</a>
									<br /><small class="text-muted">12:27 pm - 25/03/2015</small></div>
								</div>
							</li>
							<li class="divider"></li>
							<li>
								<div class="all-button"><a href="#">
									<em class="fa fa-inbox"></em> <strong>All Messages</strong>
								</a></div>
							</li>
						</ul>
					</li>
					<li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
						<em class="fa fa-bell"></em><span class="label label-info">5</span>
					</a>
						<ul class="dropdown-menu dropdown-alerts">
							<li><a href="#">
								<div><em class="fa fa-envelope"></em> 1 New Message
									<span class="pull-right text-muted small">3 mins ago</span></div>
							</a></li>
							<li class="divider"></li>
							<li><a href="#">
								<div><em class="fa fa-heart"></em> 12 New Likes
									<span class="pull-right text-muted small">4 mins ago</span></div>
							</a></li>
							<li class="divider"></li>
							<li><a href="#">
								<div><em class="fa fa-user"></em> 5 New Followers
									<span class="pull-right text-muted small">4 mins ago</span></div>
							</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar">
			<div class="profile-userpic">
				<img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
			</div>
			<div class="profile-usertitle">
				<div class="profile-usertitle-name">Username</div>
				<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		<form role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			</div>
		</form>
		<ul class="nav menu">

			<li class="active"><a href="index.html"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
			@if(Auth::user()->role=='admin')
		<li><a href="/home/creatives"><em class="fa fa-calendar">&nbsp;</em> Creatives</a></li>
		<li><a href="/home/approval"><em class="fa fa-calendar">&nbsp;</em> Approve Accounts</a></li>
		@endif
			<li><a href="widgets.html"><em class="fa fa-calendar">&nbsp;</em> Widgets</a></li>
			<li><a href="charts.html"><em class="fa fa-bar-chart">&nbsp;</em> Charts</a></li>
			<li><a href="elements.html"><em class="fa fa-toggle-off">&nbsp;</em> UI Elements</a></li>
			<li><a href="panels.html"><em class="fa fa-clone">&nbsp;</em> Alerts &amp; Panels</a></li>

			<li class="parent "><a data-toggle="collapse" href="#sub-item-1">
					<em class="fa fa-navicon">&nbsp;</em> Users <span data-toggle="collapse" href="#sub-item-1" class="icon pull-right"><em class="fa fa-plus"></em></span>
				</a>
				<ul class="children collapse" id="sub-item-1">
					<li><a class="" href="/users">
							<span class="fa fa-arrow-right">&nbsp;</span> Legite Users
						</a></li>
					<li><a class="" href="/pending_users">
							<span class="fa fa-arrow-right">&nbsp;</span> Pending
						</a></li>
				</ul>
			</li>
			<li><a href="{{ route('creative.index') }}"><em class="fa fa-clone">&nbsp;</em> Creatives</a></li>

			<li class="parent "><a data-toggle="collapse" href="#sub-item-1">
				<em class="fa fa-navicon">&nbsp;</em> Multilevel <span data-toggle="collapse" href="#sub-item-1" class="icon pull-right"><em class="fa fa-plus"></em></span>
				</a>
				<ul class="children collapse" id="sub-item-1">
					<li><a class="" href="#">
						<span class="fa fa-arrow-right">&nbsp;</span> Sub Item 1
					</a></li>
					<li><a class="" href="#">
						<span class="fa fa-arrow-right">&nbsp;</span> Sub Item 2
					</a></li>
					<li><a class="" href="#">
						<span class="fa fa-arrow-right">&nbsp;</span> Sub Item 3
					</a></li>
				</ul>
			</li>
			<li><a href="{{ route('logout') }}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
		</ul>
	</div><!--/.sidebar-->
		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		@yield('header')
		
		@yield('content')

	</div>	<!--/.main-->
	
	<script src="{{ asset('lumino/lumino/js/jquery-1.11.1.min.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/chart.min.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/chart-data.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/easypiechart.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/easypiechart-data.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/bootstrap-datepicker.js') }}"></script>
	<script src="{{ asset('lumino/lumino/js/custom.js') }}"></script>
	<script>
		window.onload = function () {
			var chart1 = document.getElementById("line-chart").getContext("2d");
			window.myLine = new Chart(chart1).Line(lineChartData, {
			responsive: true,
			scaleLineColor: "rgba(0,0,0,.2)",
			scaleGridLineColor: "rgba(0,0,0,.05)",
			scaleFontColor: "#c5c7cc"
			});
		};
	</script>
	
	@yield('javascript')
</body>
</html>